#!/bin/bash

# Copyright (c) 2011, Lawrence Livermore National Security, LLC.
# Produced at the Lawrence Livermore National Laboratory.
# LLNL-CODE-468512
#
# This file is part of lustre-tools-llnl.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License (as published by the
# Free Software Foundation) version 2, dated June 1991.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the IMPLIED WARRANTY OF
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# terms and conditions of the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
###########################################################################

# Revoke all client locks, which should write all dirty Lustre
# page cache pages and discard the clean ones.
#
# Based on flush-lustre-client-locks script by Herb Wartens.

declare nsdir
declare -r prog=lflush

vopt=0
retval=0

die()
{
    echo "${prog}: $1" >&2
    exit 1
}

warn()
{
    echo "${prog}: $1" >&2
}

lock_count()
{
    local server=$1
    local nlock nulock nres

    pushd ${nsdir} >/dev/null || die "could not chdir to ${nsdir}"
        [ "${server}" = "*" ] && die "could not find any servers"
        nlock=$(cat ${server}/lock_count 2>/dev/null)
        nulock=$(cat ${server}/lock_unused_count 2>/dev/null)
        nres=$(cat ${server}/resource_count 2>/dev/null)
    popd >/dev/null

    return $((${nlock:-0}+${nulock:-0}+${nres:-0}))
}

# Flush all locks for all servers
flush_locks()
{
    local server count

    pushd ${nsdir} >/dev/null || die "could not chdir to ${nsdir}"
        waiting=""
        for server in *; do
            [ "${server}" = "*" ] && die "could not find any servers"
            if ! lock_count ${server}; then
                [ ${vopt} = 1 ] && warn "flushing ${server}"
                echo clear >${server}/lru_size &
                child=$!
                waiting="$waiting $child"
            fi
        done
        if ! wait $waiting; then
            warn "problem flushing one or more servers; re-run with -v"
        fi
    popd >/dev/null
}

##
## MAIN
##

[ $(id -u) = 0 ] || die "must run as root"

nsdir=/sys/fs/lustre/ldlm/namespaces
if [ ! -d $nsdir ]; then
	nsdir=/proc/fs/lustre/ldlm/namespaces
fi

if [ ! -d $nsdir ]; then
    warn "lustre client is not active - nothing to do"
    exit 0
fi

while getopts "v" opt; do
    case ${opt} in
        v) vopt=1 ;;
        *) die "Usage: ${prog} [-v]" ;;
    esac
done

if [ -x /bin/sync ]; then
    /bin/sync
fi

flush_locks

exit ${retval}
