#!/usr/bin/env python

# Copyright (c) 2011, Lawrence Livermore National Security, LLC.
# Produced at the Lawrence Livermore National Laboratory.
# Written by Christopher J. Morrone <morrone2@llnl.gov>
# LLNL-CODE-468512
#
# This file is part of lustre-tools-llnl.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License (as published by the
# Free Software Foundation) version 2, dated June 1991.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the IMPLIED WARRANTY OF
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# terms and conditions of the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

import itertools
import operator
import os
import pprint
import re
import sys
import subprocess
from optparse import OptionParser

PROC_LLITE = '/proc/fs/lustre/llite'
PROC_OSC = '/proc/fs/lustre/osc'

def uuid_from_file(path, filename):
    """Works for files that have uuid and status, like "ost_server_uuid",
    and also for files that just contain the uuid, like "uuid"."""

    full_path = os.path.join(path, filename)
    return open(full_path).readline().split()[0]

def get_fs_uuid_by_name():
    """Return a dictionary of filesystem uuids.  Key is filesystem name."""

    dictionary = {}
    dirs = os.listdir(PROC_LLITE)
    for d in dirs:
        if not os.path.isdir(os.path.join(PROC_LLITE, d)):
            continue

        # Assume that the portion of the llite directory name before the
        # last "-" is the name of the filesystem.
        filesystem_name = d.rsplit('-', 1)[0]
        filesystem_uuid = uuid_from_file(os.path.join(PROC_LLITE, d), 'uuid')

        dictionary[filesystem_name] = filesystem_uuid

    return dictionary

def get_fs_name_by_mntpt():
    """Return dictionary of filesystem names.  Key is mount point."""

    d = {}
    for line in open('/proc/mounts'):
        field = line.split()
        fs_type = field[2]
        if fs_type != 'lustre':
            continue
        fs_name = field[0].split(':/')[1]
        mntpt = field[1]
        d[mntpt] = fs_name
    return d

def path_to_fs_uuid(path):
    fs_uuid_by_name = get_fs_uuid_by_name()
    fs_name_by_mntpt = get_fs_name_by_mntpt()

    path = os.path.abspath(path)
    # Keep checking dirname of path until the mount point is found.
    while True:
        if path in fs_name_by_mntpt:
            return fs_uuid_by_name[fs_name_by_mntpt[path]]
        if path == '/':
            break
        path = os.path.dirname(path)
    return None

def ostuuid_from_oscuuid(osc_name):
    path = os.path.join(PROC_OSC, osc_name+'/ost_server_uuid')

    return uuid_from_file(os.path.join(PROC_OSC, osc_name), 'ost_server_uuid')

def get_osts_by_fs_uuid():
    try:
        lfs = subprocess.Popen(['lfs', 'osts'], stdout=subprocess.PIPE)
    except:
        print >>sys.stderr, 'Unable to execute "lfs".'

    osts_info_dict = {}
    for line in lfs.stdout:
        line = line.strip()
        args = re.split('[\s:]+', line)
        if len(args) != 3:
            continue
        ost_idx = args[0]
        ost_uuid = args[1]
        ost_status = args[2]
        osts_info_dict[ost_uuid] = [ost_uuid, ost_idx, ost_status]

    # Get all of the osts on the system by walking through
    # all of the oscs on the system.  The lctl output listing
    # the oscs associates each osc with a filesystem UUID,
    # and then we can find out which ost the osc is associated with
    # from /proc.  Keep in mind that each ost can be in use by
    # multiple oscs, so just ignore the duplicates.
    try:
        lctl = subprocess.Popen(['/usr/sbin/lctl', 'dl', '-t'],
                                stdout=subprocess.PIPE)
    except:
        print >>sys.stderr, 'Unable to execute "/usr/sbin/lctl dl -t".'
        sys.exit(3)

    osts_by_filesystem = {}
    for line in lctl.stdout:
        line = line.strip()
        field = line.split()
        device_type = field[2]
        if device_type != 'osc':
            continue
        osc_name = field[3]

        filesystem_uuid = field[4]
        if filesystem_uuid not in osts_by_filesystem:
            osts_by_filesystem[filesystem_uuid] = {}
        osts_dict = osts_by_filesystem[filesystem_uuid]

        ost_uuid = ostuuid_from_oscuuid(osc_name)
        if ost_uuid in osts_dict:
            # already found this ost through another osc
            continue
        ost_nid = field[6]
        osts_info_dict[ost_uuid].append(ost_nid)
        osts_dict[ost_uuid] = osts_info_dict[ost_uuid]

    return osts_by_filesystem

def nid_sort(nida, nidb):
    a = nida.split('@')
    b = nidb.split('@')
    if a[1] != b[1]:
        return cmp(a[1], b[1])
    a = a[0].split('.')
    b = b[0].split('.')
    if len(a) != len(b):
        return cmp(len(a), len(b))
    for (x, y) in zip(a, b):
        if x != y:
            try:
                rc = cmp(int(x), int(y))
            except:
                rc = cmp(x, y)
            return rc
    return 0

def create_files(dir, num, osts, prefix, digits, verbose):
    if not os.path.isdir(dir):
        print dir, 'is not a valid directory'
        sys.exit(2)
    format = os.path.join(dir, prefix + '%0' + str(digits) + 'd')
    for i in xrange(0, num):
        filename = format % (i,)
        ost = osts.next()
        index = ost[1]
        if os.path.exists(filename):
            os.remove(filename)

        cmd = ['lfs', 'setstripe',
               '--size', '1048576',
               '--count', '1',
               '--index', index,
               filename]
        if verbose:
            print ' '.join(cmd)

        subprocess.call(cmd)

def ost_array_cmp(a, b):
    return cmp(int(a[1]), int(b[1]))

def get_osts_by_oss(osts_dict):
    result = {}

    for value in osts_dict.values():
        ost_uuid = value[0]
        ost_index = value[1]
        ost_state = value[2]
        oss_nid = value[3]

        if oss_nid not in result:
            result[oss_nid] = []
        result[oss_nid].append(value)

    # Sort OSTs by index
    for ost_list in result.values():
        ost_list.sort(cmp=ost_array_cmp)

    return result

def oss_round_robin(osts_per_oss):
    """Return an iterator that returns the next OST from the next OSS."""

    sorted_nids = osts_per_oss.keys()
    sorted_nids.sort(cmp=nid_sort)
    ost_its = [itertools.cycle(osts_per_oss[nid]) for nid in sorted_nids]
    while True:
        for i in xrange(len(ost_its)):
            yield ost_its[i].next()

def reduce_oss_count(oss_dict, num):
    """Remove OSSs from oss_dict, leaving only 'num' OSS."""

    nids = oss_dict.keys()
    if num > len(nids):
        print 'Requested OSS count', num, 'is too high.  Only', len(nids), 'OSS in this filesystem.'
        sys.exit(2)

    nids.sort(cmp=nid_sort)
    nids = nids[:num]
    for nid in oss_dict.keys():
        if nid not in nids:
            del oss_dict[nid]

    #pp = pprint.PrettyPrinter()
    #pp.pprint(oss_dict)
    #sys.exit(0)

def main():
    p = OptionParser()
    p.add_option('-d', '--directory', dest='dir', metavar='DIR',
                 help='directory in which to precreate files')
    p.add_option('-s', '--server', dest='server_nid', metavar='NID',
                 help='nid of single server where files will be create')
    p.add_option('-t', '--type', dest='file_type', metavar='FILE',
                 help='"mib" or "ior" type file names')
    p.add_option('-n', '--num-files', dest='num', type='int',
                 metavar='NUMBER', default=1,
                 help='number of files to create for mib and/or ior')
    p.add_option('--num-oss', dest='num_oss', type='int',
                 metavar='NUM_OSS')
    p.add_option("-v", "--verbose",
                 action="store_true", dest="verbose", default=False,
                 help="don't print status messages to stdout")
    (opts, args) = p.parse_args()

    if opts.server_nid and opts.num_oss:
        print '-s/--server and --num-oss parameters may not be used together'
        sys.exit(1)

    osts_by_fs_uuid = get_osts_by_fs_uuid()
    if not osts_by_fs_uuid:
        print 'No OSTs found.'
        sys.exit(1)

    if opts.dir:
        path = opts.dir
    else:
        # assume current working directory
        path = os.getcwd()

    fs_uuid = path_to_fs_uuid(path)
    if fs_uuid is None:
        print path, "is not a lustre filesystem."
        sys.exit(1)

    osts_dict = osts_by_fs_uuid[fs_uuid]

    osts_by_oss = get_osts_by_oss(osts_dict)

    if opts.server_nid:
        if opts.server_nid not in osts_by_oss:
            print 'Server NID not found'
            return 2
        osts = itertools.cycle(osts_by_oss[opts.server_nid])
    elif opts.num_oss:
        reduce_oss_count(osts_by_oss, opts.num_oss)
        osts = oss_round_robin(osts_by_oss)
    else:
        osts = oss_round_robin(osts_by_oss)

    if opts.file_type and (opts.file_type == 'ior' or opts.file_type == 'mib'):
        if opts.file_type == 'ior':
            prefix = 'ior.'
            digits = 8
        elif opts.file_type == 'mib':
            prefix = 'mibData.'
            digits = 8
        create_files(path, opts.num, osts,
                     prefix=prefix, digits=digits,
                     verbose=opts.verbose)
    else:
        print "Must specify file type with -t parameter."
        return 1

    return 0

if __name__ == '__main__':
    sys.exit(main())
